### ISSUE TITLE
deps

### ISSUE THREAD

**Issue by determin1st** [kspalaiologos/yarg#1]
dear miss, i wanted to copy your codes for PHP runtime but refrained. that header file contains fprints and other "std" output functions which doesnt quite fit sucha tool as PHP. see, the output should not be bound to those, its better to decide on integer codes.

**Comment by iczelia** [comment]
Hi,

The `<stdio.h>` functions used by this library don't actually print anything to the terminal (for a large part).

https://github.com/kspalaiologos/yarg/blob/main/yarg.h#L48 handles allocation failures by terminating and vsnprintf is used by https://github.com/kspalaiologos/yarg/blob/main/yarg.h#L52 to format error messages into a string.

Is the PHP interpreter forbidden from using the libc? If this is the case, we would have to provide substitutes for `str*` functions (e.g. `strcat`, `strcpy`), which is out of scope of this project - feel free to host your own fork!

**Comment by determin1st** [comment]
ye, oke. you position it as a library so imo its better to provide numeric error codes, because PHP (or others) formatting may be different or absent. i just want to drop unnecessary deps to improve PHP core. argument parsing is a singleton operation there. ive made a clone and compiled it several times, but building procedure is very complicated, i have to simplify it first.

**Comment by iczelia** [comment]
I designed `yarg` to be a more-or-less drop-in `getopt` replacement, because `getopt_long` is not available on a lot of non-GNU platforms and existing implementatons have weird licensing implications. I think that this library perhaps has not been made with your specific purpose in mind, but you're free to host a fork. Thanks for filing the ticket.

**Comment by determin1st** [comment]
ye, you right, i dont know what is `getopt_long`, i only know arguments :]
